#= 
  Script for plotting the data generated by GADGET3 simulation, using GADGETPlotting.jl.

  The snapshots and related data files are located in:
  ../../sim_data/results/isolated/M000_32
  ../../sim_data/results/isolated/M000_64
  ../../sim_data/results/isolated/M000_128
  ../../sim_data/results/isolated/M016_32
  ../../sim_data/results/isolated/M016_64
  ../../sim_data/results/isolated/M016_128

  The resulting figures, GIFs, and videos will be store in ../../plots/011/.
  
  Plots:
  - Histogram of gas density, with vertical lines signaling the values:

    - 1 cm^(-3)
    - 10 cm^(-3)
    - 100 cm^(-3)
    - 1000 cm^(-3)
    - 5000 cm^(-3)
    - 10000 cm^(-3)
  
  NOTE: profile plots have the animation capability disable until the issue 
  [3199](https://github.com/JuliaPlots/Plots.jl/issues/3199) is resolved.
 =#

push!(LOAD_PATH, "../GADGETPlotting/src/")
using GADGETPlotting, LaTeXStrings

"Path to the directory where the figures and animations will be saved."
const BASE_OUT_PATH = "../../plots/011"

"Path to the directory containing the simulations."
const BASE_SRC_PATH = "../../sim_data/results/isolated"

"""
The names of the directories containing the snapshot files 
and the base names of the files.
"""
const SNAPSHOTS = [
    "M000_32" "snap"
    "M000_64" "snap"
    "M000_128" "snap"
    "M016_32" "snap" 
    "M016_64" "snap"
    "M016_128" "snap" 
]

"""
Value of ComovingIntegrationOn: 
0 -> Newtonian simulation,
1 -> Cosmological simulation.
"""
const SIM_COSMO = 0

"Frame rate for the animations."
const FPS = 20

sim_paths = SNAPSHOTS[:, 1]
base_names = SNAPSHOTS[:, 2]

############################################################################################
# Histogram of gas particle's density.
############################################################################################

for (base_name, sim_path) in zip(base_names, sim_paths)
    density_histogram_pipeline(
        base_name,
        joinpath(BASE_SRC_PATH, sim_path),
        "density_histogram_animation",
        FPS,
        output_path = joinpath(BASE_OUT_PATH, "density_histogram", sim_path),
        sim_cosmo = SIM_COSMO,
        flags = (
            [
                2.471402662718477e7 / (10^10),
                2.471402662718477e8 / (10^10),
                2.471402662718477e9 / (10^10),
                2.471402662718477e10 / (10^10),
                1.2357013313592384e11 / (10^10),
                2.471402662718477e11 / (10^10)
            ], 
            [
                L"1\,\mathrm{cm}^{-3}", 
                L"10\,\mathrm{cm}^{-3}",  
                L"100\,\mathrm{cm}^{-3}",  
                L"1000\,\mathrm{cm}^{-3}",  
                L"5000\,\mathrm{cm}^{-3}",  
                L"10000\,\mathrm{cm}^{-3}", 
            ],
        ),
        step = 5,
        factor = 10,
    )
end

println("Work done!")
