#= 
  Script for plotting the data generated by GADGET3 simulations, using GADGETPlotting.jl.

  The sfr.txt files are located in:
    ../../sim_data/results/cosmological/run_00/
    ../../sim_data/results/cosmological/run_A_01/

  The figures will be store in ../../plots/005/.
  
  Plots:
    - Comparison between cosmological simulations `run_A_01` and `run_00` of 
      column 2, 3, 4, 5 y 6 vs. column 1 (time):
      - Column 2: mass probability.
      - Column 3: SFR per particle.
      - Column 4: SFR probability
      - Column 5: actual mass.
      - Column 6: actual SFR.
 =#

push!(LOAD_PATH, "../GADGETPlotting/src/")
using GADGETPlotting, Unitful, UnitfulAstro

"Path to the directory where the figures and animations will be saved."
const BASE_OUT_PATH = "../../plots/005"

"Path to the directory containing the simulations."
const BASE_SRC_PATH = "../../sim_data/results/cosmological"

"""
Names of the directories containing the snapshot files 
and the base name of the first snapshot.
"""
const SNAPSHOTS = [
    "run_00" "snapdir_000/snap_000.0"
    "run_A_01" "snapdir_000/snap_000.0"
]

"""
Value of ComovingIntegrationOn: 
0 -> Newtonian simulation.
1 -> Cosmological simulation.
"""
const SIM_COSMO = 1

sim_paths = SNAPSHOTS[:, 1]
snap_paths = SNAPSHOTS[:, 2]

labels = reshape(SNAPSHOTS[:, 1], 1, :)
titles =
    names = [
        "mass_probability_vs_t",
        "SFR_per_particle_vs_t",
        "SFR_probability_vs_t",
        "actual_mass_vs_t",
        "actual_SFR_vs_t",
    ]

############################################################################################
# Comparison between models of column 2, 3, 4, 5 y 6 vs. column 1 (time)
############################################################################################

sfr_txt_pipeline(
    snap_paths,
    joinpath.(BASE_SRC_PATH, sim_paths),
    1,
    [2, 3, 4, 5, 6];
    output_path = joinpath(BASE_OUT_PATH, "sfr_txt"),
    sim_cosmo = SIM_COSMO,
    comparison_type = 1,
    titles,
    names,
    labels,
    bins = 50,
    scale = (:identity, :log10),
    time_unit = UnitfulAstro.Gyr,
)

println("Work done!")
