#= 
  Script for plotting the data generated by GADGET3 simulations, using GADGETPlotting.jl.

  The snapshots and related data files are located in:
    ../../sim_data/results/isolated/run_00
    ../../sim_data/results/isolated/M019_TEST_03
    ../../sim_data/results/isolated/M019_64
    ../../sim_data/results/isolated/M019_128

  The resulting figures, GIFs, and videos will be store in ../../plots/018/.
  
  Plots:
    - Comparison of column 2, 3, 4, 5 y 6 vs. column 1 (time):
      - Column 2: mass probability.
      - Column 3: SFR per particle.
      - Column 4: SFR probability
      - Column 5: actual mass.
      - Column 6: actual SFR.
 =#

push!(LOAD_PATH, "../GADGETPlotting/src/")
using GADGETPlotting, Unitful, UnitfulAstro

"Path to the directory where the figures and animations will be saved."
const BASE_OUT_PATH = "../../plots/018"

"Path to the directory containing the simulations."
const BASE_SRC_PATH = "../../sim_data/results/isolated"

"""
Names of the directories containing the snapshot files 
and the base names of the files.
"""
const SNAPSHOTS = [  
    "run_00" "snap" "run_00 - 32" 
    "M019_TEST_03" "snap" "M019 - 32" 
    "M019_64" "snap" "M019 - 64"
    "M019_128" "snap" "M019 - 128"
]

"""
Value of ComovingIntegrationOn: 
0 -> Newtonian simulation.
1 -> Cosmological simulation.
"""
const SIM_COSMO = 0

titles =
    names = [
        "mass_probability_vs_t",
        "SFR_per_particle_vs_t",
        "SFR_probability_vs_t",
        "actual_mass_vs_t",
        "actual_SFR_vs_t",
    ]

sim_paths = String.(SNAPSHOTS[:, 1])
base_names = String.(SNAPSHOTS[:, 2])
labels = String.(reshape(SNAPSHOTS[:, 3], 1, :))

############################################################################################
# Comparison of column 2, 3, 4, 5 y 6 vs. column 1 (time)
############################################################################################

sfr_txt_pipeline(
    base_names .* "_000",
    joinpath.(BASE_SRC_PATH, sim_paths),
    1,
    [2, 3, 4, 5, 6];
    output_path = joinpath(BASE_OUT_PATH, "sfr_txt"),
    sim_cosmo = SIM_COSMO,
    comparison_type = 1,
    titles,
    names,
    labels,
    bins = 20,
    scale = (:identity, :log10),
    time_unit = UnitfulAstro.Gyr,
)

println("Work done!")
