#= 
  Script for plotting the data generated by GADGET3 simulations, using GADGETPlotting.jl.

  The snapshots and related data files are located in:
    ../../sim_data/results/isolated/M019_TEST_02
    ../../sim_data/results/isolated/M019_32_HSML000
    ../../sim_data/results/isolated/M019_32_HSML025
    ../../sim_data/results/isolated/M019_32_HSML050
    ../../sim_data/results/isolated/M019_32_HSML001
    ../../sim_data/results/isolated/M019_64

  The resulting figures, GIFs, and videos will be store in ../../plots/017/.
  
  Plots:
    - Comparison of column 2, 3, 4, 5 y 6 vs. column 1 (time):
      - Column 2: mass probability.
      - Column 3: SFR per particle.
      - Column 4: SFR probability
      - Column 5: actual mass.
      - Column 6: actual SFR.
    - Fmol vs. nh0 (cm^-3)
    - T (temperature) vs. ρ (density)
 =#

push!(LOAD_PATH, "../GADGETPlotting/src/")
using GADGETPlotting, Unitful, UnitfulAstro

"Path to the directory where the figures and animations will be saved."
const BASE_OUT_PATH = "../../plots/017"

"Path to the directory containing the simulations."
const BASE_SRC_PATH = "../../sim_data/results/isolated"

"""
Names of the directories containing the snapshot files 
and the base names of the files.
"""
const SNAPSHOTS = [  
    "M019_TEST_02" "snap" "M019 - New use of nh0" 
    "M019_32_HSML000" "snap" "M019_32 - hsml=0.0" 
	"M019_32_HSML025" "snap" "M019_32 - hsml=0.25" 
	"M019_32_HSML050" "snap" "M019_32 - hsml=0.5" 
    "M019_32_HSML001" "snap" "M019_32 - hsml=1.0" 
    "M019_64" "snap" "M019_64"
]

"""
Value of ComovingIntegrationOn: 
0 -> Newtonian simulation.
1 -> Cosmological simulation.
"""
const SIM_COSMO = 0

"Frame rate for the animations."
const FPS = 10

titles =
    names = [
        "mass_probability_vs_t",
        "SFR_per_particle_vs_t",
        "SFR_probability_vs_t",
        "actual_mass_vs_t",
        "actual_SFR_vs_t",
    ]

sim_paths = String.(SNAPSHOTS[:, 1])
base_names = String.(SNAPSHOTS[:, 2])
labels = String.(reshape(SNAPSHOTS[:, 3], 1, :))

############################################################################################
# Comparison of column 2, 3, 4, 5 y 6 vs. column 1 (time)
############################################################################################

sfr_txt_pipeline(
    base_names .* "_000",
    joinpath.(BASE_SRC_PATH, sim_paths),
    1,
    [2, 3, 4, 5, 6];
    output_path = joinpath(BASE_OUT_PATH, "sfr_txt"),
    sim_cosmo = SIM_COSMO,
    comparison_type = 1,
    titles,
    names,
    labels,
    bins = 20,
    scale = (:identity, :log10),
    time_unit = UnitfulAstro.Gyr,
)

############################################################################################
# Fmol vs. nh0 (cm^-3)
############################################################################################

for (path, base_name) in zip(sim_paths, base_names)
    fmol_ftom_pipeline(
        base_name,
        joinpath(BASE_SRC_PATH, path),
        "fmol_vs_ftom",
        FPS;
        output_path = joinpath(BASE_OUT_PATH, "fmol_vs_ftom", path),
        sim_cosmo = SIM_COSMO,
    )
end

############################################################################################
# T (temperature) vs. ρ (density)
############################################################################################

for (path, base_name) in zip(sim_paths, base_names)
    rho_temp_pipeline(
        base_name,
        joinpath(BASE_SRC_PATH, path),
        "rho_vs_temp_animation",
        FPS,
        output_path = joinpath(BASE_OUT_PATH, "rho_vs_temp", path),
        sim_cosmo = SIM_COSMO,
    )
end

println("Work done!")
